[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 240000000L
lib_deps = 
    lvgl/lvgl@^8.3.10
build_flags = 
    -DLV_CONF_INCLUDE_SIMPLE
    -I src