[env:esp32dev]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 240000000L
board_build.partitions = partitions.csv
board_upload.erase_first = true
board_build.psram = enable
lib_deps = 
    https://github.com/moononournation/arduino-nofrendo.git
build_flags = 
    -I .pio/libdeps/esp32dev/arduino-nofrendo/src